# Generated by Django 5.1.4 on 2024-12-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofileroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileroom',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
