# Generated by Django 5.1.4 on 2025-01-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_remove_room_users_room_name_room_reciver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
